name = "thingstodoid"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".vercel/output/static"

[env.production]
account_id = "your-account-id"
workers_dev = false
route = "thingstodo.id/*"

[[env.production.kv_namespaces]]
binding = "CACHE"
id = "your-kv-namespace-id"